Update go and fyne versions
fyne-io/fyne-cross pull request #115
Opened 2022-05-19 15:12 UTC by russellsteadman

### Description:

Updates Docker base to Go v1.18.2, Fyne v2.1.4

### Checklist:

Note: `develop` branch was already testing on Go v1.18.X in `ci.yml`

- [x] Tests included.
- [x] Lint and formatter run with no errors.
- [x] Tests all pass.

2022-05-19 16:46 UTC, Jacalz commented
Thanks for the PR. I think we were talking about getting Go 1.18 rolled out together with some other larger work but I’m not sure. Cc @lucor.

2022-05-20 20:56 UTC, lucor commented
Yes, the plan was to release a new version of fyne-cross with Go 1.18.x when fyne 2.2.0 is out.

2022-06-14 08:15 UTC, andydotxyz commented
It is time :) Plus an update with some important fixes followed, so this should now use Fyne `v2.2.1`

2022-06-14 13:31 UTC, lucor requested changes
As @andydotxyz pointed out into the comment the new version of Fyne is out :)
If you have any chance to update your PR using the latest versions of Fyne CLI and Go, we should be ready to go

2022-06-14 13:31 UTC, lucor commented on docker/base/Dockerfile
> +ARG FYNE_VERSION=v2.1.4
```suggestion
ARG FYNE_VERSION=v2.2.1
```

2022-06-14 13:54 UTC, russellsteadman commented
@lucor Updated per suggestions

2022-06-14 17:25 UTC, lucor approved these changes
Thanks

2022-06-14 17:29 UTC, merged