Feature/strip
fyne-io/fyne-cross pull request #127
Opened 2022-08-23 21:31 UTC by Bluebugs

### Description:
This enable -no-strip-debug for platform that we were actually not triggering it for (android, ios and windows) and make them equivalent as what we are doing for linux, darwin and freebsd.

Fixes #126 

### Checklist:
- [ ] Tests included.
- [ ] Lint and formatter run with no errors.
- [ ] Tests all pass.

2022-08-24 09:50 UTC, andydotxyz reviewed
I like this change, but do we need to document the behaviour change?
I think this will add `-release` parameter by default for builds. What do @lucor and @Jacalz think about this?

2022-08-24 09:51 UTC, andydotxyz commented
Also, it seems to break Android builds. Any idea what happened?

2022-08-24 09:57 UTC, andydotxyz requested changes
Ah I figured out the Android issue. Looks like this change breaks release builds as the `-release` flag is no longer respected. This seems to only be used for Android testing (see the note in container.go "// Note: at the moment this is used only for the android builds").

Checking `ctx.Release` needs to be re-added and the tests should start working again

2022-08-27 11:17 UTC, Jacalz requested changes
I found one suggestion for a comment. However, I am not quite sure what this is trying to do. Where is `ctx.StripDebug` set and why is it only checked if it isn't targeting Linux, macOS or FreeBSD?

2022-08-27 11:17 UTC, Jacalz commented on internal/command/container.go
> +// fynePackage package the application using the fyne cli tool
```suggestion
// fynePackage packages the application using the fyne cli tool
```

2022-08-28 00:04 UTC, Bluebugs commented
> I found one suggestion for a comment. However, I am not quite sure what this is trying to do. Where is `ctx.StripDebug` set and why is it only checked if it isn't targeting Linux, macOS or FreeBSD?

Other platform do not use fyne to do the build. When the build are directly done by fyne-cross it does honor the StripDebug (which is the result of a flag set on the command line). The problem was that before this, the platform build by fyne would not get stripped.

2022-08-28 08:51 UTC, Jacalz commented
Ah, I see. That makes sense but I think you might want to add a comment about that in the code. It is a bit confusing.

2022-10-18 21:35 UTC, Bluebugs commented
The change in android image are not propagated to the test and so test will still fail. If you recompile locally the image so you can have bundletool in it, everything will work as one expect.

2022-10-19 16:16 UTC, lucor submitted a review, later dismissed
LGTM. 
As discussed on the slack channel, let's have the android image updated and this tested manually as part of #134.

Before merge, do you mind to fix the small typo into the doc comment spotted by @Jacalz during the review?

2022-10-19 16:20 UTC, Bluebugs commented
Oh indeed, I tried to commit @Jacalz change from github and it failed due to some wrong email somewhere and forgot after that. Will adress.

2022-10-20 13:36 UTC, lucor approved these changes

2022-10-20 17:49 UTC, andydotxyz commented
The failed Android builds is concerning me.
It seems that the interpretation of the release has changed and now the build is attempting to package for google play instead of verifying the build process.
Adding the `bundletool` may have been an attempt to fix this, but is it the right fix? Are we attempting to do a store build in these build checks?

2022-11-10 22:42 UTC, Bluebugs commented
We should be able to move this forward with #140

2022-11-14 22:20 UTC, lucor commented
Merging is blocked since the android tests still fail.
They should pass once #141 is merged and the new docker images are available.

2022-11-15 17:47 UTC, Bluebugs commented
@Jacalz @andydotxyz with the new image with latest fyne and go, we are now all green here!

2022-11-21 13:30 UTC, andydotxyz approved these changes
Yup, Sorry I was expecting a rebase or something but it seems green now

2022-11-21 18:09 UTC, Bluebugs commented
@Jacalz would you mind checking if this PR now match your requested change earlier?

2022-11-21 18:38 UTC, Jacalz approved these changes
Sure. Looks good to me

2022-11-21 18:45 UTC, merged