Develop
fyne-io/fyne-cross pull request #183
Opened 2023-03-28 13:53 UTC by squash

### Description:

fixuid was sub-optimal for builds and spent a considerable amount of time doing unnecessary work.
This PR removes fixuid and instead sets HOME properly so that the zig compiler is able to write its cache files.
Also, if the host user's HOME is set (the general case), the host zip cache directory is mapped to the container for persistent cache between targets and subsequent builds.

Tests updated to work although tests were and continue to be broken on darwin

Fixes #181

### Checklist:

- [ x] Tests included.
- [ x] Lint and formatter run with no errors.
- [x ] Tests all pass.

2023-03-29 21:28 UTC, Bluebugs commented
The git author on those commit are not properly filled, would you mind correcting it?

2023-03-29 21:57 UTC, squash commented
I believe this has corrected it

2023-03-29 22:18 UTC, Bluebugs commented
It seems we need to handle the -no-cache case.

2023-04-11 19:54 UTC, Bluebugs requested changes

2023-04-26 16:33 UTC, squash commented on internal/command/docker_test.go
> +			want:        fmt.Sprintf("%s run --rm -t -w /app -v %s:/app:z --platform %s/%s --user %s -e HOME=/tmp -e CGO_ENABLED=1 -e GOCACHE=/go/go-build %s command arg", expectedCmd, workDir, runtime.GOOS,
This should address those points.

Also, tests now work on Darwin/arm64.

2023-04-28 20:37 UTC, Bluebugs approved these changes
This looks good. Thanks for the help figuring this.

2023-04-28 20:38 UTC, merged