Add darwin arm64 target
fyne-io/fyne-cross pull request #34
Opened 2021-03-07 18:15 UTC by lucor

This commit add support for the darwin arm64 target.

Additionally provides:
- Update Go to v1.16.0
- Update fyne cli to v2.0.1
- Add darwin arm64 target
- Remove darwin 386 target

Fixes #33

To test:
1. Clone this branch
2. [Download Xcode](https://developer.apple.com/download/more) >= 12.4 (tested against v12.4)
3. Save the XCode*.xip into the project root
4. Run `make base` to build the new `fyneio/fyne-cross:base-latest` image with Go 1.16
5. Run `make darwin` to build the `fyneio/fyne-cross:darwin-latest` image
6. compile fyne-cross from this branch
7. build and test your app

> NOTE: the creation of the image may take several minutes and may require more than 25 GB of free disk space.

2021-03-08 10:20 UTC, andydotxyz commented
This looks like a really great addition, thanks.
Unfortunately I don't have access to an M1 to test, which is probably a large chunk of this change.

2021-03-08 14:45 UTC, Jacalz reviewed
Just a few comments and ideas while I wait for the images to build:
- Would it be possible to have some sort of `fyne-cross build-darwin pathtoxcode` command to avoid having to cd into the project root and run `make` commands? Just a thought to make darwin builds easier. I don't think there would be much use for doing this for the base images.
- Would it be possible to just download the Command Line Tools instead? According to Apple, they contain all the SDK and headers needed either way. This means downloading 400 MB instead of 11 GB and make our lives a lot easier.
![image](https://user-images.githubusercontent.com/25466657/110336510-3833db80-8025-11eb-99d7-983cc33493dd.png)

2021-03-08 16:31 UTC, andydotxyz commented
> * Would it be possible to just download the Command Line Tools instead? According to Apple, they contain all the SDK and headers needed either way. This means downloading 400 MB instead of 11 GB and make our lives a lot easier.

I think you are mis-reading the information there. the 400MB file does not contain all the SDKs, it enables their use on the commandline. Those tools require XCode (and the SDKs it includes) to be present first.

2021-03-08 16:43 UTC, Jacalz commented
> > * Would it be possible to just download the Command Line Tools instead? According to Apple, they contain all the SDK and headers needed either way. This means downloading 400 MB instead of 11 GB and make our lives a lot easier.
> 
> I think you are mis-reading the information there. the 400MB file does not contain all the SDKs, it enables their use on the commandline. Those tools require XCode (and the SDKs it includes) to be present first.
> (This is based on my understanding, and extreme skepticism that their massive SDKs are possible to compress that far!)

Ah. I see now. It looks like you probably are correct.

2021-03-08 16:44 UTC, Jacalz commented
Perhaps some of the people from https://github.com/fyne-io/fyne/pull/1922, like @zdima and @sirkon could try this out as they have M1 machines? If so, it would be greatly appreciated :slightly_smiling_face:

2021-03-08 17:20 UTC, lucor commented
@Jacalz my first understanding was the same of @andydotxyz but looking closer at the osxcross doc it seems that starting from Xcode command line tools 12.x it is known to work. Let's give it a try.

> Would it be possible to have some sort of fyne-cross build-darwin pathtoxcode command to avoid having to cd into the project root and run make commands? Just a thought to make darwin builds easier. I don't think there would be much use for doing this for the base images.

Sure, in the plan this was the next step. Before implement that just want to be sure the macOS cross toolchain and image work as expected ;-)

2021-03-08 17:37 UTC, Jacalz reviewed
### Compiling
Running cross-compilation for Darwin (amd64, arm64), Linux (amd64, arm64) and FreeBSD (amd64) all completed without issues. The darwin build felt a bit slower than before, I think, now not too slow by any means (excluding the image build time). 

However, the windows build seemed to fail:
```
~/go/bin/fyne-cross windows -arch amd64 -app-id com.github.jacalz.wormhole-gui -icon internal/assets/icon/icon-512.png
[i] Target: windows/amd64
[i] Cleaning target directories...
[✓] "bin" dir cleaned: /home/jacob/go/src/github.com/Jacalz/wormhole-gui/fyne-cross/bin/windows-amd64
[✓] "dist" dir cleaned: /home/jacob/go/src/github.com/Jacalz/wormhole-gui/fyne-cross/dist/windows-amd64
[✓] "temp" dir cleaned: /home/jacob/go/src/github.com/Jacalz/wormhole-gui/fyne-cross/tmp/windows-amd64
[i] Checking for go.mod: /home/jacob/go/src/github.com/Jacalz/wormhole-gui/go.mod
[✓] go.mod found
Could not create windows resource exec: "x86_64-w64-mingw32-windres": executable file not found in $PATH
Debug output: 
[✗] could not package the Fyne app: exit status 1
make: *** [Makefile:54: windows] Error 1
```

### Running
I don't have any M1 mac to test that part on, but the following systems have been tested:
- **Linux 5.11.3 on amd64:** No issues
- **macOS 10.13 on amd64:** No issues
- **FreeBSD (GhostBSD) 12.2 on amd64:*** No issues
- **Windows 10 on amd64:** Could not test. See compilation section above.

2021-03-08 17:44 UTC, lucor commented
Thanks @Jacalz going to check the error on windows.
 
Btw it seems from first tests that using the Command_Line_Tools_for_Xcode works, at least on complilation side (does not have macOS >= 10.12 to test it).

2021-03-08 17:49 UTC, Jacalz commented
> Btw it seems from first tests that using the Command_Line_Tools_for_Xcode works, at least on complilation side (does not have macOS >= 10.12 to test it).

If you have any patch for getting that working, I’ll happily test it out on 10.13 🙂

2021-03-08 17:50 UTC, Jacalz commented
This might not be the most elegant solution out there (with all talk about not downloading random binaries from the internet). However, if anyone want to help out and test Darwin arm64 binaries on M1 machines without having to compile the fyne-cross images, I have a binary available for download here: https://github.com/Jacalz/wormhole-gui/issues/7#issuecomment-792925169

2021-03-08 17:54 UTC, lucor commented
@Jacalz added with e072d7305d4494b4f5b29bd2bd72bf0dcd75cbb0

2021-03-08 18:00 UTC, zdima commented
It is failing to start:


> On Mar 8, 2021, at 12:50 PM, Jacob <notifications@github.com> wrote:
> 
> 
> This might not be the most elegant solution out there (with all talk about not downloading random binaries from the internet). However, if anyone want to help out and test Darwin arm64 binaries on M1 machines without having to compile the fyne-cross images, I have a binary available for download here: Jacalz/wormhole-gui#7 (comment) <https://github.com/Jacalz/wormhole-gui/issues/7#issuecomment-792925169>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub <https://github.com/fyne-io/fyne-cross/pull/34#issuecomment-792947198>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/AACI2FHR4OHUPQCPDW7QDOTTCUE6BANCNFSM4YYDOZ6A>.
>

2021-03-08 18:30 UTC, lucor commented
@Jacalz windows build is fixed in 1d0ae5d. The commit also introduce a dedicated docker image for windows, to test you need to run `make windows` first.

@zdima could you please run from the terminal the `wormhole-gui.app/Contents/MacOS/warmhole-gui` binary and report the error, if any ? Thanks!

2021-03-08 18:33 UTC, zdima commented
> @zdima could you please run from the terminal the `wormhole-gui.app/Contents/MacOS/warmhole-gui` binary and report the error, if any ? Thanks!

Actually I run it from the finder and from command line. It reports damaged file in both cases.

2021-03-08 18:37 UTC, zdima commented
> > @zdima could you please run from the terminal the `wormhole-gui.app/Contents/MacOS/warmhole-gui` binary and report the error, if any ? Thanks!
> 
> Actually I run it from the finder and from command line. It reports damaged file in both cases.

I checked the system log file. Seems like MAC security is not allowing this command to run:
default	13:35:54.152787-0500	kernel	ASP: Security policy would not allow process: 4186, /Users/zdima/Downloads/wormhole-gui.app/Contents/MacOS/wormhole-gui

Is this process trying to access some protected data?

2021-03-08 18:37 UTC, Jacalz commented
Another user reported a similar error on M1. https://github.com/Jacalz/wormhole-gui/issues/7#issuecomment-792975064

2021-03-08 18:39 UTC, Jacalz commented
> > > @zdima could you please run from the terminal the `wormhole-gui.app/Contents/MacOS/warmhole-gui` binary and report the error, if any ? Thanks!
> > 
> > 
> > Actually I run it from the finder and from command line. It reports damaged file in both cases.
> 
> I checked the system log file. Seems like MAC security is not allowing this command to run:
> default 13:35:54.152787-0500 kernel ASP: Security policy would not allow process: 4186, /Users/zdima/Downloads/wormhole-gui.app/Contents/MacOS/wormhole-gui
> 
> Is this process trying to access some protected data?

It shouldn’t, as far as I know. We should probably try with something else than my project to be sure (fyne_demo perhaps). I just added a binary as I was compiling it to test fyne-cross.

2021-03-08 18:41 UTC, Jacalz commented
@lucor If we are stopping to use the docker/golang-cross image for Darwin and Windows, should we maybe stop using it altogether? The Linux support shouldn’t be too hard to wire up as is and FreeBSD doesn’t really use the either way. Just a thought 🙂

2021-03-08 18:44 UTC, zdima commented
> Another user reported a similar error on M1. [Jacalz/wormhole-gui#7 (comment)](https://github.com/Jacalz/wormhole-gui/issues/7#issuecomment-792975064)

The latest BigSur OS is very strict. You can't even exec ps command from the app.
I suspect the network layer may get restriction as well as I see many times security warnings like "app xyzy is trying access network share". A simple test app can confirm if this is the case.

2021-03-08 18:57 UTC, lucor commented
> @lucor If we are stopping to use the docker/golang-cross image for Darwin and Windows, should we maybe stop using it altogether? The Linux support shouldn’t be too hard to wire up as is and FreeBSD doesn’t really use the either way. Just a thought slightly_smiling_face

Updated the PR descrition, we already do this :) The dependency from docker/golang-cross hase been removed from the base image.

> > Another user reported a similar error on M1. [Jacalz/wormhole-gui#7 (comment)](https://github.com/Jacalz/wormhole-gui/issues/7#issuecomment-792975064)
> 
> The latest BigSur OS is very strict. You can't even exec ps command from the app.
> I suspect the network layer may get restriction as well as I see many times security warnings like "app xyzy is trying access network share". A simple test app can confirm if this is the case.

Agreed, test with a minimal "hello world app" would be great.

2021-03-08 19:36 UTC, Jacalz commented
I ran `make windows` and got this error:
```
/bin/sh: -c: line 1: syntax error near unexpected token `('
/bin/sh: -c: line 1: `docker build -f /home/jacob/Downloads/fyne-io-fyne-cross-darwin-arm64 (1)/docker/base/Dockerfile -t fyneio/fyne-cross:base-latest .'
make: *** [Makefile:4: base] Error 2
```

2021-03-08 19:38 UTC, Jacalz commented
Here is a test compile of the hello world example of https://github.com/fyne-io/fyne/blob/develop/cmd/hello/main.go:
[fyne-hello-test-darwin-arm64.zip](https://github.com/fyne-io/fyne-cross/files/6103732/fyne-hello-test-darwin-arm64.zip)

If any M1 users want to check if it works.

2021-03-08 19:53 UTC, zdima commented
> Here is a test compile of the hello world example of https://github.com/fyne-io/fyne/blob/develop/cmd/hello/main.go:
> [fyne-hello-test-darwin-arm64.zip](https://github.com/fyne-io/fyne-cross/files/6103732/fyne-hello-test-darwin-arm64.zip)
> 
> If any M1 users want to check if it works.

No luck.
However the logs are different but yet related to security.
```

default	14:46:08.783782-0500	lsd	Non-fatal error enumerating at <private>, continuing: Error Domain=NSCocoaErrorDomain Code=260 "The file “PlugIns” couldn’t be opened because there is no such file." UserInfo={NSURL=PlugIns/ -- file:///Users/zdima/Downloads/Test.app/Contents/, NSFilePath=/Users/zdima/Downloads/Test.app/Contents/PlugIns, NSUnderlyingError=0x14fe22b90 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
default	14:46:08.783852-0500	lsd	- 45683955: Checking whether application is managed at file:///Users/zdima/Downloads/Test.app//io.fyne.hello
default	14:46:08.816973-0500	lsd	SecTranslocateCreateSecureDirectoryForURL: created /private/var/folders/0l/3mf0k_35553cjfstjtm5sgj40000gn/T/AppTranslocation/24A68833-65E1-4BEC-A05F-0E2A469487CD/d/Test.app
default	14:46:08.848562-0500	kernel	AMFI: '/private/var/folders/0l/3mf0k_35553cjfstjtm5sgj40000gn/T/AppTranslocation/24A68833-65E1-4BEC-A05F-0E2A469487CD/d/Test.app/Contents/MacOS/Test' has no CMS blob?
default	14:46:08.848581-0500	kernel	AMFI: '/private/var/folders/0l/3mf0k_35553cjfstjtm5sgj40000gn/T/AppTranslocation/24A68833-65E1-4BEC-A05F-0E2A469487CD/d/Test.app/Contents/MacOS/Test': Unrecoverable CT signature issue, bailing out.
default	14:46:08.859123-0500	tccd	AUTHREQ_ATTRIBUTION: msgID=139.35, attribution={accessing={identifier=a.out, pid=4421, auid=501, euid=501, binary_path=/private/var/folders/0l/3mf0k_35553cjfstjtm5sgj40000gn/T/AppTranslocation/24A68833-65E1-4BEC-A05F-0E2A469487CD/d/Test.app/Contents/MacOS/Test}, requesting={identifier=com.apple.syspolicyd, pid=139, auid=0, euid=0, binary_path=/usr/libexec/syspolicyd}, },
default	14:46:08.862232-0500	runningboardd	Acquiring assertion targeting [app<application.io.fyne.hello.7158211.7158215(501)>:4421] from originator [daemon<com.apple.coreservices.appleevents(55)>:309] with description <RBSAssertionDescriptor| "AE/Test" ID:162-309-2950 target:4421 attributes:[
	<RBSDomainAttribute| domain:"com.apple.launchservicesd" name:"LSNotification" sourceEnvironment:"(null)">
	]>
default	14:46:08.864725-0500	loginwindow	-[PersistentAppsSupport applicationReady:] | App: Test, ready, updating active tracking timer
default	14:46:08.864787-0500	loginwindow	-[ApplicationManager checkInAppContext:eventData:] | ApplicationManager: Checked in app : Test
default	14:46:08.904558-0500	lsd	Non-fatal error enumerating at <private>, continuing: Error Domain=NSCocoaErrorDomain Code=260 "The file “PlugIns” couldn’t be opened because there is no such file." UserInfo={NSURL=PlugIns/ -- file:///var/folders/0l/3mf0k_35553cjfstjtm5sgj40000gn/T/AppTranslocation/24A68833-65E1-4BEC-A05F-0E2A469487CD/d/Test.app/Contents/, NSFilePath=/var/folders/0l/3mf0k_35553cjfstjtm5sgj40000gn/T/AppTranslocation/24A68833-65E1-4BEC-A05F-0E2A469487CD/d/Test.app/Contents/PlugIns, NSUnderlyingError=0x152e0a770 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
default	14:46:08.904797-0500	lsd	- 45683955: Checking whether application is managed at file:///var/folders/0l/3mf0k_35553cjfstjtm5sgj40000gn/T/AppTranslocation/24A68833-65E1-4BEC-A05F-0E2A469487CD/d/Test.app//io.fyne.hello
default	14:46:08.921931-0500	lsd	Non-fatal error enumerating at <private>, continuing: Error Domain=NSCocoaErrorDomain Code=260 "The file “PlugIns” couldn’t be opened because there is no such file." UserInfo={NSURL=PlugIns/ -- file:///var/folders/0l/3mf0k_35553cjfstjtm5sgj40000gn/T/AppTranslocation/24A68833-65E1-4BEC-A05F-0E2A469487CD/d/Test.app/Contents/, NSFilePath=/var/folders/0l/3mf0k_35553cjfstjtm5sgj40000gn/T/AppTranslocation/24A68833-65E1-4BEC-A05F-0E2A469487CD/d/Test.app/Contents/PlugIns, NSUnderlyingError=0x154046810 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
default	14:46:08.922158-0500	lsd	- 45683955: Checking whether application is managed at file:///var/folders/0l/3mf0k_35553cjfstjtm5sgj40000gn/T/AppTranslocation/24A68833-65E1-4BEC-A05F-0E2A469487CD/d/Test.app//io.fyne.hello
default	14:46:08.924581-0500	tccd	-[TCCDAccessIdentity staticCode]: static code for: identifier io.fyne.hello, type: 0: 0x10a812ec0 at /var/folders/0l/3mf0k_35553cjfstjtm5sgj40000gn/T/AppTranslocation/24A68833-65E1-4BEC-A05F-0E2A469487CD/d/Test.app
default	14:46:08.967648-0500	trustd	could not enable test hierarchy: no UAT pinning preferences set
default	14:46:08.988074-0500	trustd	could not enable test hierarchy: no UAT pinning preferences set
default	14:46:11.163599-0500	kernel	ASP: Security policy would not allow process: 4421, /Users/zdima/Downloads/Test.app/Contents/MacOS/Test

```

2021-03-08 20:40 UTC, Jacalz commented
Looks like the binaries require some sort of signing to be openable. I think I’ve read about that somewhere before. That might need to be hooked up into fyne-cross, I recon (if it isn’t already and I just didn’t sign it).

2021-03-09 01:37 UTC, zdima commented
> Looks like the binaries require some sort of signing to be openable. I think I’ve read about that somewhere before. That might need to be hooked up into fyne-cross, I recon (if it isn’t already and I just didn’t sign it).

Was the codesign command executed as part of the packaging?
I saw it was executed when Fyne package command run for my app.

2021-03-09 07:45 UTC, Jacalz commented
> > Looks like the binaries require some sort of signing to be openable. I think I’ve read about that somewhere before. That might need to be hooked up into fyne-cross, I recon (if it isn’t already and I just didn’t sign it).
> 
> Was the codesign command executed as part of the packaging?
> I saw it was executed when Fyne package command run for my app.

It might have, I’m honestly not sure. All I did was do `fyne-cross darwin -arch arm64`. If it doesn’t sign it, it probably should do so.

2021-03-09 09:01 UTC, lucor commented
I cursory checked the fyne CLI command for build and it seems does not sign the binary during the build phase (i.e. compiling the Go source). IIRC signing should be required only to release on the App Store but I could recall wrong. Maybe @andydotxyz can shed some light on this.

fyne-cross creates the package in two steps: 
1. compile the binary using the clang compiler provided by the toolchain
2. package using the fyne CLI tool via `fyne package`

Btw there was a typo into CC flag for the arm64 that could be the cause (fixed in 705254e7f929e52ad16a9c605eb19b4970d4b882)

@Jacalz could you please rebuild the test package/binary using the latest commit  (need to recompile fyne-cross)

If you agree I'd test also the binary from the CLI with the objective to isolate the problem.

2021-03-09 10:03 UTC, andydotxyz commented
Currently we do code signing on `fyne release` only.
We can make it a requirement for `fyne package` when arch is `M1`, though that is a frustration as it would mean developers require to pay apple to install apps on their own machine. Perhaps there is a "developer cert" that can be applied for local testing?

2021-03-09 17:56 UTC, Jacalz approved these changes
Further testing of this indicates that `windows` now builds cleanly and the binaries work when tested on Windows 10. Building for `darwin` using the command line tools also seems to work without issues (tested binaries on macOS 10.13). Now we just need to get `darwin/arm64` to work :+1:

2021-03-09 19:43 UTC, lucor commented
@Jacalz f9ae7eb signs the binary for arm64 using a fake cert (see https://github.com/tpoechtrager/osxcross/issues/227) 
Hoping this will fix

2021-03-09 20:26 UTC, Jacalz commented
> @Jacalz [f9ae7eb](https://github.com/fyne-io/fyne-cross/commit/f9ae7eb7f1b5b13cd04e32d15d2e92369c5cedda) signs the binary for arm64 using a fake cert (see [tpoechtrager/osxcross#227](https://github.com/tpoechtrager/osxcross/issues/227))
> Hoping this will fix

Splendid. I will spin up new test binaries as soon as I have the time to do so 🙂

2021-03-09 20:41 UTC, Jacalz commented
Alright peeps. New "fake" signed binary up for testing:
[fyne-cross-test2-darwin-arm64.zip](https://github.com/fyne-io/fyne-cross/files/6111293/fyne-cross-test2-darwin-arm64.zip)

2021-03-09 20:53 UTC, zdima commented
> Alright peeps. New "fake" signed binary up for testing:
> [fyne-cross-test2-darwin-arm64.zip](https://github.com/fyne-io/fyne-cross/files/6111293/fyne-cross-test2-darwin-arm64.zip)
No changes. I think the signing process is off.
``Test-2.app/Contents/MacOS/Test' has no CMS blob``

Check this info https://research.dynastic.co/2019/01/31/coretrust-overview on CMS Blob.

2021-03-10 19:24 UTC, lucor commented
Yep, it looks like need further investigation :(

Btw it seems that osxcross was already signing the binary, if so latest commit is not needed.

@zdima or any other M1 user, just to retrieve further info could you please  run `codesign -dv --verbose=4 <binary_name>`
against the binaries from the following ?
- https://github.com/fyne-io/fyne-cross/files/6103732/fyne-hello-test-darwin-arm64.zip
- https://github.com/fyne-io/fyne-cross/files/6111293/fyne-cross-test2-darwin-arm64.zip
- the binary obtained from the compilation of https://github.com/fyne-io/fyne/blob/develop/cmd/hello/main.go on the M1

2021-03-10 20:31 UTC, zdima commented
> @zdima or any other M1 user, just to retrieve further info could you please run `codesign -dv --verbose=4 <binary_name>`
> against the binaries from the following ?

> * https://github.com/fyne-io/fyne-cross/files/6103732/fyne-hello-test-darwin-arm64.zip
$ codesign -dv --verbose=4 ./Test.app/Contents/MacOS/Test 
Executable=/Users/zdima/Downloads/Test.app/Contents/MacOS/Test
Identifier=a.out
Format=app bundle with Mach-O thin (arm64)
CodeDirectory v=20400 size=74366 flags=0x20002(adhoc,linker-signed) hashes=2321+0 location=embedded
VersionPlatform=1
VersionMin=720896
VersionSDK=721152
Hash type=sha256 size=32
CandidateCDHash sha256=1513bceff1161c17a06bd0ae30d651a04fb13d6c
CandidateCDHashFull sha256=1513bceff1161c17a06bd0ae30d651a04fb13d6c1ea3aaa51469e9546f0ff564
Hash choices=sha256
CMSDigest=1513bceff1161c17a06bd0ae30d651a04fb13d6c1ea3aaa51469e9546f0ff564
CMSDigestType=2
Executable Segment base=0
Executable Segment limit=3309568
Executable Segment flags=0x1
Page size=4096
CDHash=1513bceff1161c17a06bd0ae30d651a04fb13d6c
Signature=adhoc
Info.plist=not bound
TeamIdentifier=not set
Sealed Resources=none
Internal requirements=none

> * https://github.com/fyne-io/fyne-cross/files/6111293/fyne-cross-test2-darwin-arm64.zip
$ codesign -dv --verbose=4 ./Test.app/Contents/MacOS/Test 
Executable=/Users/zdima/Downloads/Test.app/Contents/MacOS/Test
Identifier=Test
Format=app bundle with Mach-O thin (arm64)
CodeDirectory v=20400 size=74429 flags=0x0(none) hashes=2321+2 location=embedded
VersionPlatform=1
VersionMin=720896
VersionSDK=721152
Hash type=sha256 size=32
CandidateCDHash sha1=067e57cc2e8181fccda214f4da6859252601fc54
CandidateCDHashFull sha1=067e57cc2e8181fccda214f4da6859252601fc54
CandidateCDHash sha256=38eb332d398446daacc4b3e0c52e35e41fb7e410
CandidateCDHashFull sha256=38eb332d398446daacc4b3e0c52e35e41fb7e4106964a0d3e0a860790641529a
Hash choices=sha1,sha256
CMSDigest=1c68ce4b88d818b8db1a91328f90fe7b2b110a7d15b0db51fa0adb6d6eb9c7b6
CMSDigestType=2
Page size=4096
CDHash=38eb332d398446daacc4b3e0c52e35e41fb7e410
./Test.app/Contents/MacOS/Test: no signature
Info.plist=not bound
TeamIdentifier=not set
Sealed Resources=none
Internal requirements count=1 size=120


> * the binary obtained from the compilation of https://github.com/fyne-io/fyne/blob/develop/cmd/hello/main.go on the M1
$ codesign -dv --verbose=4 ./test 
Executable=/System/Volumes/Data/Network/Servers/mars.local.cloud/mnt/sweep/workfolder/zdima/test/test
Identifier=a.out
Format=Mach-O thin (arm64)
CodeDirectory v=20400 size=93438 flags=0x20002(adhoc,linker-signed) hashes=2917+0 location=embedded
VersionPlatform=1
VersionMin=720896
VersionSDK=721152
Hash type=sha256 size=32
CandidateCDHash sha256=7790214727ea9fd0516017e0fa05701a8bdd51db
CandidateCDHashFull sha256=7790214727ea9fd0516017e0fa05701a8bdd51db96eac56a771163dcd43c6031
Hash choices=sha256
CMSDigest=7790214727ea9fd0516017e0fa05701a8bdd51db96eac56a771163dcd43c6031
CMSDigestType=2
Executable Segment base=0
Executable Segment limit=3112960
Executable Segment flags=0x1
Page size=4096
CDHash=7790214727ea9fd0516017e0fa05701a8bdd51db
Signature=adhoc
Info.plist=not bound
TeamIdentifier=not set
Sealed Resources=none
Internal requirements=none

2021-03-11 08:06 UTC, Jacalz requested changes
Came we get Go upgraded to 1.16.1 while we’re at it? It includes some rather important security fixes https://mobile.twitter.com/golang/status/1369690242681278464.

2021-03-11 18:26 UTC, lucor commented
> Came we get Go upgraded to 1.16.1 while we’re at it? It includes some rather important security fixes https://mobile.twitter.com/golang/status/1369690242681278464.

Updated in 27c55af

2021-03-12 06:28 UTC, Jacalz requested changes
Sorry for the bad timing. Go 1.16.2 has been released as well. Can we get it  updated? 😅

2021-03-12 08:12 UTC, lucor commented
Updated to Go v1.16.2 in c95deca

2021-03-12 22:59 UTC, lucor commented
Root cause could be the wrong macos min version used to compile for arm64, updated in 0d36b99
Feedback using that commit for fyne-cross and the latest docker image with 1.16.2 would be great.
If possible please test using  the `--no-string-debug` flag too:
- `fyne-cross darwin --app-id com.example.test --arch arm64 --no-cache`
- `fyne-cross darwin --app-id com.example.test --arch arm64 --no-cache --no-strip-debug`

2021-03-13 11:32 UTC, Jacalz commented
Here are two new M1 test applications for testing. One is without debug and the other is with debug symbols:
[fyne-cross-darwin-arm64-test-no-debug.zip](https://github.com/fyne-io/fyne-cross/files/6134685/fyne-cross-darwin-arm64-test-no-debug.zip)
[fyne-cross-darwin-arm64-test-with-debug.zip](https://github.com/fyne-io/fyne-cross/files/6134689/fyne-cross-darwin-arm64-test-with-debug.zip)

2021-03-13 11:33 UTC, Jacalz commented
Things are looking much better now. I am getting the same deprecation warnings as https://github.com/fyne-io/fyne/issues/1833, which I take as a good sign that the binaries are correctly built :slightly_smiling_face:

2021-03-13 13:15 UTC, zdima commented
> Here are two new M1 test applications for testing. One is without debug and the other is with debug symbols:
> [fyne-cross-darwin-arm64-test-no-debug.zip](https://github.com/fyne-io/fyne-cross/files/6134685/fyne-cross-darwin-arm64-test-no-debug.zip)
> [fyne-cross-darwin-arm64-test-with-debug.zip](https://github.com/fyne-io/fyne-cross/files/6134689/fyne-cross-darwin-arm64-test-with-debug.zip)
A bit different this time:
`default	08:10:50.334913-0500	kernel	ASP: Security policy would not allow process: 12374, /Users/zdima/Downloads/Test-2.app/Contents/MacOS/Test`

Are these binaries signed with developer profile?
There could be a latest OS restriction to not run any app unless there is a developer profile behind it.
These are only options OS allowed, and I assume app will not run unless there is a signature that can be verified.
![Screen Shot 2021-03-13 at 8 09 06 AM](https://user-images.githubusercontent.com/298260/111031018-72113300-83d3-11eb-8d06-be02a76645fa.png)

2021-03-13 13:18 UTC, zdima commented
Check this article. Perhaps adding entitlement  com.apple.developer.endpoint-security.client will solve security issue.
https://developer.apple.com/forums/thread/666123

2021-03-13 14:00 UTC, lucor commented
Oh, great! So it looks like is working :-)

With regard to the warning above, this is expected. Go is using an ad-hoc signature, so unless you sign again the binary with a cert with a vality identity it cannot pass through Gatekeeper (see https://github.com/golang/go/issues/42684#issuecomment-730037844 and the official docs https://developer.apple.com/documentation/macos-release-notes/macos-big-sur-11_0_1-universal-apps-release-notes#Code-Signing for details)

Details on how open a developer-signed or notarized app can be found on the apple support site: https://support.apple.com/en-us/HT202491

The plan is to found a way to sign the binary using a valid cartificate directly from linux, but I'd say that this is another issue.

On macOS you would sing using a developer certificate using either the `fyne release` command or directly the `codesign` tool.

@zdima could you please confirm if it runs after allowing the execution from an unidentified developer?

2021-03-13 15:09 UTC, zdima commented
That is the thing. Latest Big Sur don't have an option to run the app from unidentified source. I am not getting "Open anyway" option and can't find if I can enable it.

2021-03-13 15:36 UTC, lucor commented
Did you tried by any chance the following from the macOS user guide: https://support.apple.com/guide/mac-help/open-a-mac-app-from-an-unidentified-developer-mh40616/mac ?
> To override your security settings and open the app anyway follow these steps:
> 1. In the Finder on your Mac, locate the app you want to open.  
Don’t use Launchpad to do this. Launchpad doesn’t allow you to access the shortcut menu.
> 2. Control-click the app icon, then choose Open from the shortcut menu.
> 3. Click Open. 
The app is saved as an exception to your security settings, and you can open it in the future by double-clicking it just as you can any registered app.
>
> Note: You can also grant an exception for a blocked app by clicking the Open Anyway button in the General pane of Security & Privacy preferences. This button is available for about an hour after you try to open the app.
>
> To change these preferences on your Mac, choose Apple menu  > System Preferences, click Security & Privacy, then click General.

2021-03-13 16:10 UTC, zdima commented
Yes. I did. Multiple times.
I think without developer certificate this not going to work. At least on M1 with latest OS.
Do we know if it works on Mac with x86-64?
I believe the developer certificate can be obtained for free once you register as developer on apple dev site. Unless you want to publish the app in the store, no payment require.

2021-03-13 16:27 UTC, Jacalz commented
I found this article https://www.kencochrane.com/2020/08/01/build-and-sign-golang-binaries-for-macos-with-github-actions/. It might be kind of useful. However, it still looks like you need a paid developer account to be able to get signing certificates https://developer.apple.com/support/compare-memberships.

2021-03-13 17:12 UTC, lucor commented
> Yes. I did. Multiple times.
> I think without developer certificate this not going to work. At least on M1 with latest OS.

It could be, but it is hard to debug without a physical access to an M1 :-(

@zdima To check if the if the signature is valid could you please run: `codesign -v -vvvv —ignore-resources <path/to/binary>` on both binaries above ?

> Do we know if it works on Mac with x86-64?

Yes, it works as reported by @Jacalz  above. The restriction applies only to latest macOS on M1

2021-03-13 17:48 UTC, Jacalz commented
> > Do we know if it works on Mac with x86-64?
> 
> Yes, it works as reported by @Jacalz above. The restriction applies only to latest macOS on M1

Though, we should keep in mind that it was tested on MacOS 10.13. Someone running Big Sur on an amd64 machine should probably test as well. I think @andydotxyz has one?

2021-03-13 18:22 UTC, zdima commented
> @zdima To check if the if the signature is valid could you please run: `codesign -v -vvvv —ignore-resources <path/to/binary>` on both binaries above ?

This is output:
``` $ codesign -v -vvvv --ignore-resources  /Applications/Test-2.app/Contents/MacOS/Test 
/Applications/Test-2.app/Contents/MacOS/Test: valid on disk (not all contents verified)
/Applications/Test-2.app/Contents/MacOS/Test: satisfies its Designated Requirement```

2021-03-13 19:46 UTC, lucor commented
> > @zdima To check if the if the signature is valid could you please run: `codesign -v -vvvv —ignore-resources <path/to/binary>` on both binaries above ?
> 
> This is output:
> 
> ```
> /Applications/Test-2.app/Contents/MacOS/Test: valid on disk (not all contents verified)
> /Applications/Test-2.app/Contents/MacOS/Test: satisfies its Designated Requirement
> ```

Thanks @zdima. This is weird...  as per the official [doc](https://developer.apple.com/documentation/macos-release-notes/macos-big-sur-11_0_1-universal-apps-release-notes#Code-Signing) the signature is valid for the policy:
> To check the validity of a signature, run codesign -v -vvvv —ignore-resources <path to mach-O>. If the command indicates “valid on disk (not all contents verified)” and “satisfies its Designated Requirement”, the code is valid under this policy.

Let's try o recap where we are so far:
- fyne application is cross compiled  for arm64 using Go 1.16.2 against the SDK 1.11
- the application is signed using an ad hoc certificate by Go
- the signature is valid when checked with codesign
- the application is downloaded from internet
- fyne apps built natively on arm64 are known to work out of the box.
- cross-compiled app runs on macOS 10.13 amd64, we expect it should also run on macOS 11.x amd64 since codesigning is required only on arm64.

Issue: we are unable to run on macOS 11.x arm64 a cross-compiled app with fyne-cross on macOS amd64 due to Gatekeeper policy issues. We have not found a way yet to open an app from an unidentiefied developer despite the [doc says]( https://support.apple.com/guide/mac-help/open-a-mac-app-from-an-unidentified-developer-mh40616/mac) it should be possible.

Things comes in mind to debug the issue above:
1. build a fyne app natively on arm64 -> upload somewhere -> download and run on arm64
2. build a fyne app with fyne-cross on arm64 for arm64 -> run locally
3. check additional steps that would allow installation of apps from unidentiefied developer (and downloaded from internet ?)

Missed something ? Any additional ideas ?

2021-03-13 20:29 UTC, andydotxyz commented
> Though, we should keep in mind that it was tested on MacOS 10.13. Someone running Big Sur on an amd64 machine should probably test as well. I think @andydotxyz has one?

Current build tools work on BigSur for x86_64 yes - no signing required (though you will get warnings if the file was downloaded without signing).

2021-03-13 20:59 UTC, andydotxyz commented
Obviously on an x86_64 BigSur those built M1 binaries won't run.
However I ran fyne-cross to build for darwin and that ran on BigSur for me (x86_64).

2021-03-14 17:31 UTC, Jacalz reviewed
I built for `FreeBSD` and got this error:
```
[i] Building binary...
# runtime/cgo
/usr/local/bin/x86_64-unknown-freebsd11-clang: 2: exec: clang: not found
[✗] exit status 2
make: *** [Makefile:45: freebsd] Error 1
```

2021-03-15 11:53 UTC, Jacalz commented
Thanks @lucor. That works now :+1:

2021-03-15 18:48 UTC, lucor commented
Here is a new M1 test applications for testing: [test.zip](https://github.com/fyne-io/fyne-cross/files/6143723/test.zip)

It tries a possible fix for the linker.

2021-03-31 06:58 UTC, merged